# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Bluse
SEOTitle: Bluse
subtitle: Programing Thinker
description: "..."
author: bluse wang
language: zh-CN
timezone: PRC

header-img: "https://www.sslcentral.com/wp-content/uploads/2014/09/sld1.jpg"
email: dev.jf.wang@gmail.com

github_username: blusewang

# Sidebar settings
sidebar: true
sidebar-about-description: "因为凡人，所以烦人！"
sidebar-avatar: "https://avatars0.githubusercontent.com/u/1764005?v=3&s=460"

# post default images
post-default-img: "https://3hsyn13u3q9dhgyrg2qh3tin-wpengine.netdna-ssl.com/wp-content/uploads/2015/03/SplitShire-8098-1800x1200.jpg"
post-default-img-mobile: "https://3hsyn13u3q9dhgyrg2qh3tin-wpengine.netdna-ssl.com/wp-content/uploads/2015/03/SplitShire-8098-1800x1200.jpg"

favicon: ""

# friends
friends: [{title: "ruff",href: 'https://ruff.io/zh-cn/'}]


tagcloud: true

# search api , set your custom key
swiftype_key:


# archive page title
archive:
    title: archives
    description: 可以根据归档日期检索所有文件


# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://www.wangjunfeng.com.cn
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: docs
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: Anisina

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repo: https://github.com/blusewang/blog.git
  branch: master
